#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import PoseStamped

def set_goal(x, y):
    pub = rospy.Publisher('/move_base_simple/goal', PoseStamped, queue_size=10)
    rospy.init_node('set_goal', anonymous=True)
    goal = PoseStamped()
    goal.header.frame_id = "map"
    goal.header.stamp = rospy.Time.now()
    goal.pose.position.x = x
    goal.pose.position.y = y
    goal.pose.orientation.w = 1.0
    
    pub.publish(goal)
    rospy.loginfo("Goal set to: ({}, {})".format(x, y))

if __name__ == "__main__":
    try:
        set_goal(1.0, 1.0)  # Belirli bir hedef noktasına gitmesi için çağır.
    except rospy.ROSInterruptException:
        pass

